name: Deploy WordPress to Ubuntu Server

on:
  push:
    branches:
      - develop  # Replace with your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH agent to authenticate with your server
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.test-secret }}

      # Step 3: Add your server's IP address to known_hosts to prevent SSH from asking for confirmation
      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H 18.143.66.206  >> ~/.ssh/known_hosts
      # Step 4: Deploy the code to the server (syncing /var/www/html)
      - name: Deploy to server
        run: |
          rsync -avz --delete-after --exclude '.git' ./ ubuntu@18.143.66.206:/var/www/html/test
      # Step 5 (optional): Set proper permissions on the server
      - name: Set permissions
        run: |
          ssh ubuntu@18.143.66.206  'sudo chown -R www-data:www-data /var/www/html/test && sudo chmod -R 755 /var/www/html/test'
